status          = "approved"
id              = "ghostscript"
version         = "10.0.0"
summary         = "PostScript and PDF interpreter"
arch            = "x86_64"
abi             = "v1"
category        = "utility/print"
url             = "https://archives.arosworld.org/share/utility/print/ghostscript-10.0.0.x86_64-aros.lha"
size            = 12826633
sha256          = "7953164a91c1b63db3aeb177631e2e85c612f03907a958f795c255d715a6e7c6"
kind            = "app"
depends         = []
depends_checked = true
subdir          = "Ghostscript-10.0.0"
